spoonacular:
  apiKey: 81f81ed2617548ee9b23fbf3eb50a445

edamam:
  app_id: b20fad02
  app_key: 22dac3a0e0885328a6a320875a6eef93

spring:
#  profiles.active: dev
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
#      ddl-auto: update